@HostAddress = http://localhost:5212

### Categories - Get all
GET {{HostAddress}}/api/Categories

### Categories - Get by id
GET {{HostAddress}}/api/Categories/6

### Categories - Get products by category id
GET {{HostAddress}}/api/Categories/6/products

### Categories - Create
POST {{HostAddress}}/api/Categories
Content-Type: application/json

{
  "name": "Books",
  "description": "Books and reading materials"
}

### Categories - Update
PUT {{HostAddress}}/api/Categories/7
Content-Type: application/json

{
  "name": "Books Updated",
  "description": "Updated books and reading materials"
}

### Categories - Delete
DELETE {{HostAddress}}/api/Categories/8


### Products - Get all
GET {{HostAddress}}/api/Products

### Products - Get by id
GET {{HostAddress}}/api/Products/3

### Products - Create
POST {{HostAddress}}/api/Products
Content-Type: application/json

{
  "name": "Phone: Iphone 17 Pro Max",
  "price": 1399.99,
  "stock": 25,
  "categoryId": 6
}

### Products - Update
PUT {{HostAddress}}/api/Products/3
Content-Type: application/json

{
  "name": "Phone: Samsung Galaxy S21",
  "price": 1299.99,
  "stock": 15,
  "categoryId": 6
}

### Products - Delete
DELETE {{HostAddress}}/api/Products/3

